### ISSUE TITLE
Trimming test

### ISSUE THREAD

**Issue by kianenigma** [paritytech/staking-miner-v2#207]
We don't really have a good scenario about how to test trimming. This is a crucial pare of the code path of the staking miner and should be tested here as well (it is already being tested to some extent in the EPM pallet).

**Comment by niklasad1** [comment]
After the `staking miner playground` was introduced now supports changing the `block length` and `block weight` at runtime by submitting signed extrinsics.

However, this doesn't help us to test the trimming in the staking miner as it reads these constants from the metadata and changing the values have no effect until the metadata is upgraded.

Thus, this is really tricky to test without doing an actual runtime upgrade or hard-code `MinerMaxLength, `MinerMaxWeight` and the etc at compile-time.

**Comment by niklasad1** [comment]
Closed by #538
