### ISSUE TITLE
gitlab failed nightly job doesn't report back status

### ISSUE THREAD

**Issue by niklasad1** [paritytech/staking-miner-v2#406]
The nightly job [here](https://gitlab.parity.io/parity/mirrors/staking-miner-v2/-/jobs/1997506) failed but it doesn't report back status.

Not sure why that is, could be that it was killed because it exceeded the max execution time.
Can you have a look please @sergejparity? 

I added some more timeout recently so I hope time gitlab timeout won't be exceeded but would be good that status is sent back anyway.

**Comment by sergejparity** [comment]
Yes, it fails exactly because of the timeout. In such case `after_script` section where job status saved does not executed. And `nightly-test-notification` job cannot get the status, because it wasn't saved. Will take a look what we can do about it.
