### ISSUE TITLE
v0.1.1 fails to compile; error[E0308]: mismatched types

### ISSUE THREAD

**Issue by dcolley** [paritytech/staking-miner-v2#445]
$ rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.64.0 (a55dd71d5 2022-09-19)`

$ cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)

Steps to replicate:
```bash
git clone https://github.com/paritytech/staking-miner-v2
cd staking-miner-v2
cargo install --locked subxt-cli
subxt metadata --url ws://localhost:30325 -f bytes > artifacts/metadata.scale
subxt codegen --file artifacts/metadata.scale | rustfmt +nightly > code.rs
cargo build --release --locked
```

Error:

```rs
   Compiling staking-miner v0.1.1 (/usr/src/staking-miner-v2)
error[E0308]: mismatched types
   --> src/monitor.rs:375:6
    |
375 |     for (_score, _, idx) in indices.0 {
    |         ^^^^^^^^^^^^^^^^    --------- this is an iterator with items of type `(sp_npos_elections::ElectionScore, u32)`
    |         |
    |         expected a tuple with 2 elements, found one with 3 elements
    |
    = note: expected tuple `(sp_npos_elections::ElectionScore, u32)`
               found tuple `(_, _, _)`

error[E0308]: mismatched types
   --> src/monitor.rs:407:18
    |
407 |         .map_or(true, |(best_score, _, _)| score_passes_strategy(score, *best_score, strategy))
    |                        ^^^^^^^^^^^^^^^^^-
    |                        |                |
    |                        |                expected due to this
    |                        expected a tuple with 2 elements, found one with 3 elements
    |
    = note: expected tuple `(sp_npos_elections::ElectionScore, u32)`
               found tuple `(_, _, _)`
```

**Comment by niklasad1** [comment]
hey @dcolley 

why are you updating the metadata file?
staking-miner v2 supports > v9330 and I guess you are trying to run an older version locally.

Maybe try https://github.com/paritytech/staking-miner-v2/releases/tag/v0.1.4-alpha instead then.

However, if you update the metadata file these kind of compile errors might occur FWIW.

**Comment by dcolley** [comment]
Updating the meta file is in the instructions...?

**Comment by dcolley** [comment]
I managed to get it to compile now.

> staking-miner v2 supports > v9330
Where is this documented? If it's a requirement then I suggest you update the README.

It won't run against a local node - I get this error even though --uri is a valid OPTION?

```bash
target/release/staking-miner dry-run --uri ws://localhost:30325
error: Found argument '--uri' which wasn't expected, or isn't valid in this context

	If you tried to supply `--uri` as a value rather than a flag, use `-- --uri`

USAGE:
    staking-miner dry-run [OPTIONS] --seed-or-path <SEED_OR_PATH> <SUBCOMMAND>

For more information try --help
```

**Comment by niklasad1** [comment]
> Where is this documented? If it's a requirement then I suggest you update the README.

We document that in release notes but sure we could add it in the README as well, fair enough. See https://github.com/paritytech/staking-miner-v2/releases/tag/v0.1.1

> It won't run against a local node - I get this error even though --uri is a valid OPTION?

It works but the order is just wrong.
This should work:

`$ staking-miner --uri ws://localhost:30325 dry-run --seed-or-path <SEED> seq-phragmen`

**Comment by dcolley** [comment]
Confirmed, thanks!
I think the usage should be updated to reflect that syntax. The `--uri` option is part of OPTIONS?

```
USAGE:
    staking-miner dry-run [OPTIONS] --seed-or-path <SEED_OR_PATH> <SUBCOMMAND>
```

**Comment by niklasad1** [comment]
If you run `staking-miner help` the options should be shown but yeah it's tricky to get those sub-commands in correct order.
